version: "3.3"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile

    ports:
      - 3000:3000
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile

    ports:
      - 3001:3000
